---
- name: Create Slurm users
  hosts: localhost
  become: false

  vars:
    slurm_users:
    #update this var
      - name: fzhang
        default_account: rci
        admin_level: None
      - name: wulf
        default_account: feng-group
        admin_level: None

  tasks:
    #- name: Debug slurm_users
    #  ansible.builtin.debug:
    #    var: slurm_users
    #
    #  Map accounts to be unique  
    - name: Get unique default accounts
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ slurm_users | map(attribute='default_account') | unique | list }}"


    - name: Query accounts
      command:
        argv:
          - sacctmgr
          - -nP
          - show
          - account
          - "{{ item }}"
      register: account_check
      changed_when: false
      failed_when: false
      loop: "{{ slurm_users | map(attribute='default_account') | unique | list }}"  

    - name: Check account results
      ansible.builtin.debug:
          msg: "Account does not exist. Creating it..."
      when: item.stdout == ""
      loop: "{{ account_check.results }}"

    - name: Create accounts
      command:
        argv:
          - sacctmgr
          - -i
          - add
          - account
          - "name={{ item.item }}"
          - "parent=clinwulf"
        #      - "Description={{ item.item.description }}"
        #- "Organization={{ item.item.organization }}"
      when: item.stdout == ""
      failed_when: false  
      loop: "{{ account_check.results }}"

    # Now work on users
    - name: Query existing users
      command:
        argv:
          - sacctmgr
          - -nP
          - show
          - user
          - "{{ item.name }}"
      register: user_check
      changed_when: false
      failed_when: false
      loop: "{{ slurm_users }}"
      tags: query_user

    - name: Check users results
      ansible.builtin.debug:
          msg: "User does not exist. Creating it..."
      when: item.stdout == ""
      failed_when: false        
      loop: "{{ user_check.results }}"


    - name: Create users
      command:
        argv:
          - sacctmgr
          - -i
          - add
          - user
          - "{{ item.item.name }}"
          - "DefaultAccount={{ item.item.default_account }}"
          - "AdminLevel={{ item.item.admin_level }}"
      when: item.stdout == ""
      failed_when: false        
      loop: "{{ user_check.results }}"
      tags: tocreate

    - name: Update default account
      command:
        argv:
          - sacctmgr
          - -i
          - modify
          - user
          - where
          - "name={{ item.item.name }}"
          - set
          - "DefaultAccount={{ item.item.default_account }}"
      when: item.stdout != "" 
      failed_when: false        
      loop: "{{  user_check.results }}"
      tags: toupdate
