---
- name: Configure common HPC operating system settings
  hosts: all
  become: true

  roles:

    - common
    - chrony
    - sssd
    - infiniband
    - ssh-hardening

    - selinux

    - firewall

    - audit      
