---
- name: Configure Lustre clients
  hosts: compute:gpu
  become: true

  roles:

    - lustre-client


- name: Configure GPFS clients
  hosts: compute:gpu
  become: true

  roles:

    - gpfs-client

